server:
  port: 8080
calendar:
  search-limit-days: 30
  check-work-time-limit: true
  max-working-period-duration: 86400
  max-meeting-duration: 86400
  meeting-schedule-items-limit: 20
spring:
  security:
    token-lifetime: 86400
    cookie-name: calendarAuthCookie
    cookie-token-signing-key: secretkeyforsubscribeauthtoken
  datasource:
    url: jdbc:postgresql://192.168.1.100:7689/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: calendar
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      fail-on-empty-beans: false
    mapper:
      accept-case-insensitive-enums: true
  flyway:
    schemas: calendar